version: '3.3'

services:

  sample:
    container_name: le-cherut
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: "npm start"
    tty: true